export const FARM_LIST_REQUEST = 'FARM_LIST_REQUEST';
export const FARM_LIST_SUCCESS = 'FARM_LIST_SUCCESS';
export const FARM_LIST_FAIL = 'FARM_LIST_FAIL';

export const FARM_DETAILS_REQUEST = 'FARM_DETAILS_REQUEST';
export const FARM_DETAILS_SUCCESS = 'FARM_DETAILS_SUCCESS';
export const FARM_DETAILS_FAIL = 'FARM_DETAILS_FAIL';
