export const SUBSCRIPTION_CREATE_REQUEST = 'SUBSCRIPTION_CREATE_REQUEST';
export const SUBSCRIPTION_CREATE_SUCCESS = 'SUBSCRIPTION_CREATE_SUCCESS';
export const SUBSCRIPTION_CREATE_FAIL = 'SUBSCRIPTION_CREATE_FAIL';
export const SUBSCRIPTION_CREATE_RESET = 'SUBSCRIPTION_CREATE_RESET';

export const SUBSCRIPTION_DETAILS_REQUEST = 'SUBSCRIPTION_DETAILS_REQUEST';
export const SUBSCRIPTION_DETAILS_SUCCESS = 'SUBSCRIPTION_DETAILS_SUCCESS';
export const SUBSCRIPTION_DETAILS_FAIL = 'SUBSCRIPTION_DETAILS_FAIL';

export const SUBSCRIPTION_PAY_REQUEST = 'SUBSCRIPTION_PAY_REQUEST';
export const SUBSCRIPTION_PAY_SUCCESS = 'SUBSCRIPTION_PAY_SUCCESS';
export const SUBSCRIPTION_PAY_FAIL = 'SUBSCRIPTION_PAY_FAIL';
export const SUBSCRIPTION_PAY_RESET = 'SUBSCRIPTION_PAY_RESET';

export const SUBSCRIPTION_LIST_MY_REQUEST = 'SUBSCRIPTION_LIST_MY_REQUEST';
export const SUBSCRIPTION_LIST_MY_SUCCESS = 'SUBSCRIPTION_LIST_MY_SUCCESS';
export const SUBSCRIPTION_LIST_MY_FAIL = 'SUBSCRIPTION_LIST_MY_FAIL';
export const SUBSCRIPTION_LIST_MY_RESET = 'SUBSCRIPTION_LIST_MY_RESET';

export const SUBSCRIPTION_LIST_REQUEST = 'SUBSCRIPTION_LIST_REQUEST';
export const SUBSCRIPTION_LIST_SUCCESS = 'SUBSCRIPTION_LIST_SUCCESS';
export const SUBSCRIPTION_LIST_FAIL = 'SUBSCRIPTION_LIST_FAIL';

export const SUBSCRIPTION_UPDATE_REQUEST = 'SUBSCRIPTION_UPDATE_REQUEST';
export const SUBSCRIPTION_UPDATE_SUCCESS = 'SUBSCRIPTION_UPDATE_SUCCESS';
export const SUBSCRIPTION_UPDATE_FAIL = 'SUBSCRIPTION_UPDATE_FAIL';
export const SUBSCRIPTION_UPDATE_RESET = 'SUBSCRIPTION_UPDATE_RESET';

export const SUBSCRIPTION_DELIVER_REQUEST = 'SUBSCRIPTION_DELIVER_REQUEST';
export const SUBSCRIPTION_DELIVER_SUCCESS = 'SUBSCRIPTION_DELIVER_SUCCESS';
export const SUBSCRIPTION_DELIVER_FAIL = 'SUBSCRIPTION_DELIVER_FAIL';
export const SUBSCRIPTION_DELIVER_RESET = 'SUBSCRIPTION_DELIVER_RESET';

export const SUBSCRIPTION_CANCEL_REQUEST = 'SUBSCRIPTION_CANCEL_REQUEST';
export const SUBSCRIPTION_CANCEL_SUCCESS = 'SUBSCRIPTION_CANCEL_SUCCESS';
export const SUBSCRIPTION_CANCEL_FAIL = 'SUBSCRIPTION_CANCEL_FAIL';
export const SUBSCRIPTION_CANCEL_RESET = 'SUBSCRIPTION_CANCEL_RESET';
